### ISSUE TITLE
Example of use?

### ISSUE THREAD

**Issue by krisaoe** [archmoj/grib2class#2]
Hi, could you give an example of how to read a grib file using this tool? Thanks in advance.

**Comment by archmoj** [comment]
@krisaoe this script may be helpful: https://github.com/archmoj/opengrib2/blob/master/opengrib2.js

**Comment by archmoj** [comment]
@krisaoe wondering if you managed to run the program?

**Comment by krisaoe** [comment]
@archmoj yes that helped, and I got it running. I should have read the README properly before asking for assitance. Apologies.
It works well with the supplied gribs, but unfortunately I haven't been able to get any of my grib2 files running (I assume it's because we don't use jpeg2000 compression, will look into this).
Thanks for the help.

**Comment by archmoj** [comment]
> @archmoj yes that helped, and I got it running. I should have read the README properly before asking for assitance. Apologies.
> It works well with the supplied gribs, but unfortunately I haven't been able to get any of my grib2 files running (I assume it's because we don't use jpeg2000 compression, will look into this).
> Thanks for the help.

@krisaoe
The tool should support other compression formats. 
With the [Java/Processing version](https://github.com/archmoj/grib2_solarchvision) which is the source of this JavaScript tool, I was able to work with different datasets:
https://github.com/archmoj/grib2_solarchvision/blob/77c8d0b41a7843f1a4334a596dd4759b72a28e3b/grib2_solarchvision.pde#L184-L374
Anyway please let me know if you noticed any issue.
Thank you!

**Comment by kylebarron** [comment]
I agree that a little bit of documentation would really help. I'm unable to read a GRIB from NOAA NDFD
https://tgftp.nws.noaa.gov/SL.us008001/ST.opnl/DF.gr2/DC.ndfd/AR.conus/VP.001-003/ds.ptornado.bin

```js
var grib2class = require('grib2class')
var {readFileSync} = require('fs')
var grib = new grib2class({
        numMembers: 1,
        log: false,
    });

var buf = readFileSync('./ds.ptornado.bin')
grib.parse(buf)
grib.getGrib2Section(0)
//Int32Array [
//   0, 32, 75, 87, 78, 83, 32,
//  48, 49, 49, 56, 50, 48, 13,
//  13, 10, 42
//]
```
The file is 360KB, so it's definitely larger than that array. `grib.getGrib2Section(1)` returns nothing.

**Comment by archmoj** [comment]
@kylebarron is your file in `grib2` format?

**Comment by kylebarron** [comment]
Yes, [according to NOAA](https://www.weather.gov/mdl/ndfd_data_grid) all of these files are 

> `DF.gr2/`: WMO GRIB files: Edition two, also known as GRIB2

**Comment by archmoj** [comment]
First 80 bytes of that input file is not standard, if you can trim that. 
A grib2 file should start with `GRIB`.

**Comment by archmoj** [comment]
@kylebarron 
I removed first 80 bytes and [here](https://github.com/archmoj/opengrib2/commit/13022b38846c8d6c4a3865299e169dfeba3b4281) is a commit on `opengrib2` repo to open your input.

**Comment by kylebarron** [comment]
Oh thanks! [This page](https://www.weather.gov/mdl/grib_design) describes how they encode their files, but I didn't realize the non-GRIB parts weren't standard. I'll take a look

**Comment by archmoj** [comment]
@kylebarron I use to post-prcess [these datasets](https://github.com/archmoj/grib2_solarchvision/blob/77c8d0b41a7843f1a4334a596dd4759b72a28e3b/grib2_solarchvision.pde#L243-L266) from NOAA/NCEP and using the original program written in Java. All those records as well as CMC (CCMEP) operational GRIB2 files start with `GRIB` in their headers, I think.
