### ISSUE TITLE
Getting "undefined" reference error

### ISSUE THREAD

**Issue by kngai** [archmoj/grib2class#3]
https://github.com/archmoj/grib2class/blob/a4730169516fc532298385b0115d7a254e50d3f8/grib2class.js#L1588

Hi @archmoj, just checking out this API to read grib2 files in JavaScript. That line is causing me to get a "reference" error when I attempt to `.parse()`.

I fixed it in my environment and the error went away with this change: 
- from this: 
```js
if (this.Bitmap_Indicator === 0) {
```
- to this: 
```js
if (lThis.Bitmap_Indicator === 0) {
```

I was unsure if that original `this` was intentional. If not, I can submit a PR for the fix.

Aside from the issue, I couldn't get any parsed details of the grib files I was testing with (meta, DataTitles, DataValues, Year, Month, etc...). I was testing a few grib2 files in:

https://dd.weather.gc.ca/model_hrdps/
https://dd.weather.gc.ca/model_gem_global/
I couldn't find much documentation on this, so I had to look at the code to get an idea. So perhaps I'm not using the API correctly. I'm using vue.js to create a very simple simple grib2class viewer. Here's what I have so far if you're interested (vue component file):

```html
  <div>
    <strong>Filename:</strong> <code>{{ grib2Filename }}</code>

    <h3>Parsed file details</h3>
    <v-row>
      <v-col>
        <p
          v-for="part in grib2Parts"
          :key="part">
          <strong>{{ part }}</strong>: <code>{{ grib2Reader[part] }}</code>
        </p>
      </v-col>
    </v-row>
  </div>
```

```js
import GRIB2CLASS from 'grib2class'
import axios from 'axios'

export default {
  name: 'Grib2ClassViewer',
  mounted: function () {
    let options = {
      log: false
    }
    this.grib2Reader = new GRIB2CLASS(options)
    axios.get('/static/' + this.grib2Filename)
      .then((response) => {
        this.grib2Reader.parse(response.data)
        this.grib2Reader.printMore(0, 10)
      })
  },
  data () {
    return {
      grib2Filename: 'CMC_hrdps_west_TMP_ISBL_0750_ps2.5km_2020040106_P000-00.grib2',
      grib2Reader: {},
      grib2Parts: ['meta', 'ParameterNameAndUnit', 'DataTitles', 'DataValues', 'DataAllocated', 'LengthOfMessage', 'IdentificationOfCentre', 'IdentificationOfSubCentre', 'Year', 'Month', 'Day', 'Hour', 'Minute', 'Second', 'ForecastTimeInDefinedUnits', 'ForecastConvertedTime', 'TypeOfData', 'TypeOfProjection']
    }
  }
}
```

**Comment by kngai** [comment]
Oops, my apologies. I just found this example of how to use the API: https://github.com/archmoj/grib2class/issues/2

I'll take a look further in that example and adjust my code.

**Comment by archmoj** [comment]
@kngai FYI - I fixed the `this` and published a new patch.

**Comment by archmoj** [comment]
There is a live version of that script (using old grib2 files) at https://archmoj.github.io/opengrib2/ which extracts various CMC grib2 files.
@kngai glad you are going to make use of this library.
Please let me know if you need any assistant.

**Comment by kngai** [comment]
Perfect, thanks @archmoj , I'll check that live sample out.
